### ISSUE TITLE
Unable to run on OSX 10.14.5

### ISSUE THREAD

**Issue by acollier88** [Picovoice/cheetah#14]
Running in a virutalenv
```
(env) andrews-mbp:cheetah-master andrew$ python demo/python/cheetah_demo_realtime.py 
dlopen(demo/python/../../lib/linux/x86_64/libpv_cheetah.so, 6): no suitable image found.  Did find:
	demo/python/../../lib/linux/x86_64/libpv_cheetah.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/andrew/Downloads/cheetah-master/lib/linux/x86_64/libpv_cheetah.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```
Both commands not working
```
(env) andrews-mbp:cheetah-master andrew$ python demo/python/cheetah_demo.py --audio_paths resources/audio_samples/test.wav
Traceback (most recent call last):
  File "demo/python/cheetah_demo.py", line 54, in <module>
    license_path=args.license_path)
  File "demo/python/../../binding/python/cheetah.py", line 56, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(demo/python/../../lib/linux/x86_64/libpv_cheetah.so, 6): no suitable image found.  Did find:
	demo/python/../../lib/linux/x86_64/libpv_cheetah.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/andrew/Downloads/cheetah-master/lib/linux/x86_64/libpv_cheetah.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by acollier88** [comment]
Reread the page that free edition only supports linux
