### ISSUE TITLE
cheetah-python

### ISSUE THREAD

**Issue by max00xam** [Picovoice/cheetah#196]
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ python --version
Python 3.7.3

$cheetah_demo_file --access_key xxxxxxxxxxxxxx --wav_paths audio.ogg
Traceback (most recent call last):
  File "/bin/cheetah_demo_file", line 8, in <module>
    sys.exit(main())
  File "/lib/python3.7/site-packages/pvcheetahdemo/cheetah_demo_file.py", line 46, in main
    enable_automatic_punctuation=not args.disable_automatic_punctuation)
  File "/lib/python3.7/site-packages/pvcheetah/_factory.py", line 49, in create
    enable_automatic_punctuation=enable_automatic_punctuation)
  File "/lib/python3.7/site-packages/pvcheetah/_cheetah.py", line 125, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by pvcheetah/lib/raspberry-pi/cortex-a53/libpv_cheetah.so)

**Comment by max00xam** [comment]
Ok, I think I need bullseye...
