### ISSUE TITLE
Cheetah Issue: Unable to start mic demo on MacOS 14.1.2 with M1 processor

### ISSUE THREAD

**Issue by thekevinbrown** [Picovoice/cheetah#291]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Cheetah docs
- [X] I have searched the existing issues for Cheetah

### SDK

Node.js

### Cheetah package version

2.0.0

### Framework version

@picovoice/cheetah-node-demo on nodejs v18.16.0

### Platform

macOS (x86_64, arm64)

### OS/Browser version

macOS 14.1.2 (23B92)

### Describe the bug

```
$ cheetah-mic-demo --access_key (access key redacted)
/Users/kevin/.nvm/versions/node/v18.16.0/lib/node_modules/@picovoice/cheetah-node-demo/node_modules/@picovoice/cheetah-node/dist/errors.js:88
            throw new CheetahActivationError(errorMessage, messageStack);
                  ^

CheetahActivationError: Cheetah failed to initialize: 
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `0000012C`)
    at pvStatusToException (/Users/kevin/.nvm/versions/node/v18.16.0/lib/node_modules/@picovoice/cheetah-node-demo/node_modules/@picovoice/cheetah-node/dist/errors.js:88:19)
    at Cheetah.handlePvStatus (/Users/kevin/.nvm/versions/node/v18.16.0/lib/node_modules/@picovoice/cheetah-node-demo/node_modules/@picovoice/cheetah-node/dist/cheetah.js:184:46)
    at new Cheetah (/Users/kevin/.nvm/versions/node/v18.16.0/lib/node_modules/@picovoice/cheetah-node-demo/node_modules/@picovoice/cheetah-node/dist/cheetah.js:72:18)
    at micDemo (/Users/kevin/.nvm/versions/node/v18.16.0/lib/node_modules/@picovoice/cheetah-node-demo/mic.js:77:24)
    at Object.<anonymous> (/Users/kevin/.nvm/versions/node/v18.16.0/lib/node_modules/@picovoice/cheetah-node-demo/mic.js:129:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  _message: 'Cheetah failed to initialize',
  _messageStack: [
    'Picovoice Error (code `00000136`)',
    'Picovoice Error (code `00000136`)',
    'Picovoice Error (code `0000012C`)'
  ]
}
```

### Steps To Reproduce

Follow the steps here: https://github.com/Picovoice/cheetah?tab=readme-ov-file#nodejs-demo

### Expected Behavior

Expected demo to run and demonstrate speech to text capabilities

**Comment by kenarsa** [comment]
Do you have internet connectivity on your machine? Is there a firewall? from the error, it seems the program cannot reach our servers to authenticate your `AccessKey`.

**Comment by thekevinbrown** [comment]
Oh, right! My company does blocking of certain sites, and you must have been caught up in that. Didn't realise that's what this was.

I'd recommend a specific human-readable error message in this case so people like me can self service this error. Sorry for the noise!
