### ISSUE TITLE
Issue with the realtime_demo.py demo

### ISSUE THREAD

**Issue by Technerder** [Picovoice/cheetah#4]
When running the file it prints this out and crashes:

```
Traceback (most recent call last):
  File "C:\Users\Technerder\Desktop\cheetah-master\cheetah-master\demo\python\realtime_demo.py", line 113, in <module>
    cheetah = init_cheetah(args)
  File "C:\Users\Technerder\Desktop\cheetah-master\cheetah-master\demo\python\cheetah_demo.py", line 60, in init_cheetah
    license_file_path=args.license_file_path)
  File "C:\Users\Technerder\Desktop\cheetah-master\cheetah-master\demo\python\../../binding/python\cheetah.py", line 46, in __init__
    self._libc = CDLL(ctypes.util.find_library('c'))
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
```

**Comment by kenarsa** [comment]
What's the OS?

**Comment by Venryx** [comment]
As mentioned here: https://github.com/Picovoice/cheetah/issues/7#issuecomment-514694361, this should really be mentioned in the readme.

It's fine if you don't want the open-source version to support Windows/Mac (to increase interest in the commercial version), but please be up-front about what this particular repository is compatible with.

As it stands, it just wastes people's time as they see "Mac and Windows are supported", they download the repo, install the python dependencies manually (which aren't listed as install steps btw: `pip install soundfile` and `pip install pyaudio`), and try to run the demos just to get a cryptic error.

**Comment by mehrdadfeller** [comment]
@Venryx Repo language updated to reflect that. Thanks for the feedback

**Comment by Venryx** [comment]
Nice! Thank you for the quick response. :)
