### ISSUE TITLE
[Error] License file has incorrect format

### ISSUE THREAD

**Issue by jwg4096** [Picovoice/cheetah#40]
Hi,
I see you have addressed this issue before, but I seem to have the same one.  I have the supported version of Linux, on a x86_64 machine, but still have the same problem.

I started with a clean clone of the git repo.

My license file name, reflecting that it is new, and the hash which I compared with a fresh copy of the .lic file to ensure it wasn't corrupt:
```
user@user:~/cheetah$ md5sum cheetah_eval_linux_expires_july_9th_2020.lic 
dc02f2a8e9d2cc75e0fb4602bef9381b  cheetah_eval_linux_expires_july_9th_2020.lic
```
and my version of Ubuntu:
```
user@user:~/cheetah$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
The architecture:
```
user@user:~/cheetah$ uname -a
Linux user 4.15.0-96-generic #97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
and
```
user@user:~/cheetah$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Model name:            Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
Stepping:              7
CPU MHz:               890.012
CPU max MHz:           3200.0000
CPU min MHz:           800.0000
BogoMIPS:              4989.12
Virtualisation:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3
```
Here is the output:
```
user@user:~/cheetah$ python3 demo/python/cheetah_demo.py --audio_paths resources/audio_samples/test.wav --license_path cheetah_eval_linux_expires_july_9th_2020.lic
[ERROR] license file has incorrect format
Traceback (most recent call last):
  File "demo/python/cheetah_demo.py", line 61, in <module>
    license_path=args.license_path)
  File "demo/python/../../binding/python/cheetah.py", line 92, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]('Initialization failed')
ValueError: Initialization failed
```
Note that I had to use pip3, as pip (and python 2.x seem to be deprecated).

Any help you could give would be great.  I am really keen to try this out.

**Comment by kenarsa** [comment]
provide absolute path for "--license_path" and see if that helps. I think something is wrong there.

**Comment by jwg4096** [comment]
Ah, it was my Python install.  I was sitting on 3.5.2.  I tried to install Cheetah on a Raspberry Pi 4 running Ubuntu 20.04 (3.8.2 pre-installed), and the errors I was getting were completely different, but not related to the .lic file.

After a process of elimination, I worked it out.  I also upgraded my Linux laptop to Ubuntu 20.04 and cheetah worked fine, with some tinkering.

Note that the install instructions did not work for me.  I had to carry out the following to prep the machine for cheetah:

```
sudo apt update
sudo apt upgrade
python --version
	> Python 3.8.2
sudo apt install python3-pip
pip3 --version
	> pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
sudo pip3 install numpy
sudo apt install libasound2-dev
sudo apt install portaudio19-dev
sudo apt install ffmpeg
sudo pip3 install pyaudio
sudo apt install python3-cffi
sudo pip3 install soundfile
```
Which gave me:

```
user@user:~/cheetah$ python3 demo/python/cheetah_demo.py --audio_paths resources/audio_samples/test.wav --license_path cheetah_eval_linux_expires_july_9th_2020.lic 
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited.
 [WARN] you may transcribe files that are shorter than '100' seconds.
 [WARN] your evaluation license will expire in 56 days
MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL
```
Success!  Thanks for your kind help.

**Comment by jwg4096** [comment]
I think I read that you will not make cheetah available for Pi 4 somewhere, but I can't find it now.  Is that still correct?

**Comment by kenarsa** [comment]
cheetah is available on RPI4 now. But only for enterprises who are commercially-engaged with Picovoice.
