### ISSUE TITLE
unknown file type error while running cheetah with demo file

### ISSUE THREAD

**Issue by dmytrobr** [Picovoice/cheetah#8]
I'm running sample command with Python 3.5.0 on MacOS 10.14.3

Dmytros-MBP:cheetah dmytro$ python3 demo/python/cheetah_demo.py --audio_paths resources/audio_samples/test.wav
Traceback (most recent call last):
  File "demo/python/cheetah_demo.py", line 67, in <module>
    cheetah = init_cheetah(args)
  File "demo/python/cheetah_demo.py", line 60, in init_cheetah
    license_file_path=args.license_file_path)
  File "demo/python/../../binding/python/cheetah.py", line 51, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/Users/dmytro/.pyenv/versions/3.5.0/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/Users/dmytro/.pyenv/versions/3.5.0/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/dmytro/dtf/cheetah/demo/python/../../lib/linux/x86_64/libpv_cheetah.so, 6): no suitable image found.  Did find:
	/Users/dmytro/dtf/cheetah/demo/python/../../lib/linux/x86_64/libpv_cheetah.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/dmytro/dtf/cheetah/lib/linux/x86_64/libpv_cheetah.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by kenarsa** [comment]
The engine on GitHub only runs on Linux:

https://github.com/Picovoice/cheetah#license
